name: New release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get binaries
        id: binaries
        shell: pwsh
        run: |
            Install-Module -Name MarkdownPS -Confirm:$false -Force

            $Date = Get-Date -Format "yyyy-MM-dd"
            echo "release=$Date.${{ github.run_number }}" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append

            $ChangeLogFile = "${{ github.workspace }}/changelog.txt"
            echo "# Release summary :package:" | Out-File -FilePath $Env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
            "# Release summary :package:" | Out-File -FilePath $ChangeLogFile -Encoding utf8 -Append

            $Versions = Import-Csv -Path "${{ github.workspace }}/binaries.csv" -ErrorAction "Stop"
            echo $($Versions | New-MdTable) | Out-File -FilePath $Env:GITHUB_STEP_SUMMARY -Encoding utf8 -Append
            $Versions | New-MdTable | Out-File -FilePath $ChangeLogFile -Encoding utf8 -Append

            $ProgressPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue
            $Path = "${{ github.workspace }}/release"
            New-Item -Path $Path -ItemType "Directory"
            foreach ($Item in $Versions) {
                $params = @{
                    ErrorAction     = "Continue"
                    OutFile         = $(Join-Path -Path $Path -ChildPath $Item.Filename)
                    Uri             = "${{ secrets.BLOB_URL }}$($Item.Filename)"
                    UseBasicParsing = $true
                }
                Invoke-WebRequest @params
            }

      # Upload release
      - name: Upload release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          body_path: ${{ github.workspace }}/changelog.txt
          files: |
            ${{ github.workspace }}/release/*
